version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikon2283@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgdata:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
    
  web:
    build: app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 1488
    ports:
      - 1488:1488
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - PATH=/bin:$PATH
    
volumes:
  pgdata:
  db-data: